# Generated by Django 3.1.6 on 2021-02-06 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210206_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='followers',
            field=models.ForeignKey(blank=True, help_text='Введите название группы', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followers', to='api.follow', verbose_name='Группа'),
        ),
    ]
