# Generated by Django 3.1.6 on 2021-02-06 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_post_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='followers',
        ),
    ]
