# Generated by Django 3.1.6 on 2021-02-06 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_post_followers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='following',
            new_name='author',
        ),
    ]
